name: 'Get AWS Secrets'
description: 'Retrieves secrets from AWS Secrets Manager, Parameter Store, or files'
author: 'DevOpspolis <rick@devopspolis.com>'
# branding icons https://github.com/haya14busa/github-action-brandings
branding:
  icon: unlock
  color: purple
inputs:
  secrets:
    description: A list of AWS Secrets to retrieve (space separated)
    required: true
  secrets-filter:
    description: Include only these keys from the secrets (space separated)
    required: false
    default: ''
  role:
    description: AWS role to assume
    type: string
    required: false
  aws-region:
    description: AWS region to use
    type: string
    required: false
  default-value:
    description: Default value to set for secret-keys that are not found
    type: string
    required: false
    default: ''
  preset-secrets:
    description: JSON string with preset key-value secrets to merge with retrieved secrets
    type: string
    required: false
    default: '{}'

outputs:
  secrets:
    description: Secret key value pairs (JSON)
    value: ${{ steps.get-aws-secrets.outputs.secrets }}
  secrets-filter:
    description: Space separated list of secret keys returned
    value: ${{ steps.get-aws-secrets.outputs.secrets-filter }}
  secrets-count:
    description: Number of secrets returned
    value: ${{ steps.get-aws-secrets.outputs.secrets-count }}
runs:
  using: composite
  steps:
    - name: Set AWS_REGION
      shell: bash
      run: |
        region="${{ inputs.aws-region }}"
        if [[ -z "$region" ]]; then
          region="${{ env.AWS_REGION }}"
        fi
        if [[ -z "$region" ]]; then
          region="${{ env.AWS_DEFAULT_REGION }}"
        fi
        if [[ -z "$region" ]]; then
          region="us-east-1"
        fi
        echo "AWS_REGION=$region" >> $GITHUB_ENV
        echo "✅ Using AWS region: $region"

    - name: Resolve role ARN if short name
      if: ${{ inputs.role }}
      id: resolve-role
      shell: bash
      run: |
        role="${{ inputs.role }}"
        if [[ "$role" != arn:aws:iam::* ]]; then
          echo "Resolving short role name to full ARN..."
          if [[ -z "$AWS_ACCOUNT_ID" ]]; then
            echo "❌ AWS_ACCOUNT_ID environment variable is required when using short role names"
            exit 1
          fi
          role="arn:aws:iam::${AWS_ACCOUNT_ID}:role/$role"
        fi
        echo "role_arn=$role" >> $GITHUB_OUTPUT
        echo "✅ Using role: $role"

    - name: Configure AWS credentials (if role specified)
      if: ${{ inputs.role }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.resolve-role.outputs.role_arn }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install boto3
      shell: bash

    - name: Get AWS Secrets
      id: get-aws-secrets
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        python get-aws-secrets.py
      env:
        SECRETS: ${{ inputs.secrets }}
        SECRETS_FILTER: ${{ inputs.secrets-filter }}
        DEFAULT_VALUE: ${{ inputs.DEFAULT_VALUE }}
        PRESET_SECRETS: ${{ inputs.PRESET_SECRETS }}
        AWS_REGION: ${{ env.AWS_REGION }}

